/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'radhika' at '2/27/17 11:59 PM' with Gradle 3.0
 *
 * @author radhika, @date 2/27/17 11:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
